FROM golang:1.16.14-alpine3.15

WORKDIR /usr/local/go/src/github.com/NikhilSharma03/noteman-go-grpc
RUN apk --no-cache add ca-certificates git

RUN export GO111MODULE=on

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . .

RUN cd ./services/notes && go build -v -o main

EXPOSE 3001

CMD ["./services/notes/main"]