FROM golang:1.16.14-alpine3.15

RUN apk --no-cache add ca-certificates git
WORKDIR /usr/local/go/src/github.com/NikhilSharma03/noteman-go-grpc

RUN export GO111MODULE=on
COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . .

RUN cd ./api && go build -v -o main

EXPOSE 8000

CMD ["./api/main"]