// Code generated by protoc-gen-go. DO NOT EDIT.
// source: note.proto

package notespb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Note struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Creator              string   `protobuf:"bytes,3,opt,name=creator,proto3" json:"creator,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Note) Reset()         { *m = Note{} }
func (m *Note) String() string { return proto.CompactTextString(m) }
func (*Note) ProtoMessage()    {}
func (*Note) Descriptor() ([]byte, []int) {
	return fileDescriptor_640dafe07df50d4e, []int{0}
}

func (m *Note) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Note.Unmarshal(m, b)
}
func (m *Note) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Note.Marshal(b, m, deterministic)
}
func (m *Note) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Note.Merge(m, src)
}
func (m *Note) XXX_Size() int {
	return xxx_messageInfo_Note.Size(m)
}
func (m *Note) XXX_DiscardUnknown() {
	xxx_messageInfo_Note.DiscardUnknown(m)
}

var xxx_messageInfo_Note proto.InternalMessageInfo

func (m *Note) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Note) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Note) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Note) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreateNoteRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	NoteDetails          *Note    `protobuf:"bytes,2,opt,name=note_details,json=noteDetails,proto3" json:"note_details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNoteRequest) Reset()         { *m = CreateNoteRequest{} }
func (m *CreateNoteRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNoteRequest) ProtoMessage()    {}
func (*CreateNoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_640dafe07df50d4e, []int{1}
}

func (m *CreateNoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNoteRequest.Unmarshal(m, b)
}
func (m *CreateNoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNoteRequest.Marshal(b, m, deterministic)
}
func (m *CreateNoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNoteRequest.Merge(m, src)
}
func (m *CreateNoteRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNoteRequest.Size(m)
}
func (m *CreateNoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNoteRequest proto.InternalMessageInfo

func (m *CreateNoteRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CreateNoteRequest) GetNoteDetails() *Note {
	if m != nil {
		return m.NoteDetails
	}
	return nil
}

type CreateNoteResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	NoteDetails          *Note    `protobuf:"bytes,2,opt,name=note_details,json=noteDetails,proto3" json:"note_details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNoteResponse) Reset()         { *m = CreateNoteResponse{} }
func (m *CreateNoteResponse) String() string { return proto.CompactTextString(m) }
func (*CreateNoteResponse) ProtoMessage()    {}
func (*CreateNoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_640dafe07df50d4e, []int{2}
}

func (m *CreateNoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNoteResponse.Unmarshal(m, b)
}
func (m *CreateNoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNoteResponse.Marshal(b, m, deterministic)
}
func (m *CreateNoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNoteResponse.Merge(m, src)
}
func (m *CreateNoteResponse) XXX_Size() int {
	return xxx_messageInfo_CreateNoteResponse.Size(m)
}
func (m *CreateNoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNoteResponse proto.InternalMessageInfo

func (m *CreateNoteResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateNoteResponse) GetNoteDetails() *Note {
	if m != nil {
		return m.NoteDetails
	}
	return nil
}

type GetNoteRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNoteRequest) Reset()         { *m = GetNoteRequest{} }
func (m *GetNoteRequest) String() string { return proto.CompactTextString(m) }
func (*GetNoteRequest) ProtoMessage()    {}
func (*GetNoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_640dafe07df50d4e, []int{3}
}

func (m *GetNoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNoteRequest.Unmarshal(m, b)
}
func (m *GetNoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNoteRequest.Marshal(b, m, deterministic)
}
func (m *GetNoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNoteRequest.Merge(m, src)
}
func (m *GetNoteRequest) XXX_Size() int {
	return xxx_messageInfo_GetNoteRequest.Size(m)
}
func (m *GetNoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNoteRequest proto.InternalMessageInfo

func (m *GetNoteRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *GetNoteRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GetNoteResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	NoteDetails          []*Note  `protobuf:"bytes,2,rep,name=note_details,json=noteDetails,proto3" json:"note_details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNoteResponse) Reset()         { *m = GetNoteResponse{} }
func (m *GetNoteResponse) String() string { return proto.CompactTextString(m) }
func (*GetNoteResponse) ProtoMessage()    {}
func (*GetNoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_640dafe07df50d4e, []int{4}
}

func (m *GetNoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNoteResponse.Unmarshal(m, b)
}
func (m *GetNoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNoteResponse.Marshal(b, m, deterministic)
}
func (m *GetNoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNoteResponse.Merge(m, src)
}
func (m *GetNoteResponse) XXX_Size() int {
	return xxx_messageInfo_GetNoteResponse.Size(m)
}
func (m *GetNoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNoteResponse proto.InternalMessageInfo

func (m *GetNoteResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetNoteResponse) GetNoteDetails() []*Note {
	if m != nil {
		return m.NoteDetails
	}
	return nil
}

type NoteRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoteRequest) Reset()         { *m = NoteRequest{} }
func (m *NoteRequest) String() string { return proto.CompactTextString(m) }
func (*NoteRequest) ProtoMessage()    {}
func (*NoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_640dafe07df50d4e, []int{5}
}

func (m *NoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoteRequest.Unmarshal(m, b)
}
func (m *NoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoteRequest.Marshal(b, m, deterministic)
}
func (m *NoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoteRequest.Merge(m, src)
}
func (m *NoteRequest) XXX_Size() int {
	return xxx_messageInfo_NoteRequest.Size(m)
}
func (m *NoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NoteRequest proto.InternalMessageInfo

func (m *NoteRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type NoteResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	NoteDetails          []*Note  `protobuf:"bytes,2,rep,name=note_details,json=noteDetails,proto3" json:"note_details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoteResponse) Reset()         { *m = NoteResponse{} }
func (m *NoteResponse) String() string { return proto.CompactTextString(m) }
func (*NoteResponse) ProtoMessage()    {}
func (*NoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_640dafe07df50d4e, []int{6}
}

func (m *NoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoteResponse.Unmarshal(m, b)
}
func (m *NoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoteResponse.Marshal(b, m, deterministic)
}
func (m *NoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoteResponse.Merge(m, src)
}
func (m *NoteResponse) XXX_Size() int {
	return xxx_messageInfo_NoteResponse.Size(m)
}
func (m *NoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NoteResponse proto.InternalMessageInfo

func (m *NoteResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *NoteResponse) GetNoteDetails() []*Note {
	if m != nil {
		return m.NoteDetails
	}
	return nil
}

func init() {
	proto.RegisterType((*Note)(nil), "notes.Note")
	proto.RegisterType((*CreateNoteRequest)(nil), "notes.CreateNoteRequest")
	proto.RegisterType((*CreateNoteResponse)(nil), "notes.CreateNoteResponse")
	proto.RegisterType((*GetNoteRequest)(nil), "notes.GetNoteRequest")
	proto.RegisterType((*GetNoteResponse)(nil), "notes.GetNoteResponse")
	proto.RegisterType((*NoteRequest)(nil), "notes.NoteRequest")
	proto.RegisterType((*NoteResponse)(nil), "notes.NoteResponse")
}

func init() { proto.RegisterFile("note.proto", fileDescriptor_640dafe07df50d4e) }

var fileDescriptor_640dafe07df50d4e = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x69, 0xda, 0x10, 0xf5, 0x52, 0x15, 0x71, 0x14, 0x64, 0x3a, 0x55, 0x66, 0x61, 0xca,
	0x50, 0x18, 0x59, 0x68, 0x41, 0x6c, 0x0c, 0x9d, 0xf8, 0x23, 0x81, 0xd2, 0xe6, 0x04, 0x16, 0x69,
	0x1c, 0x62, 0x33, 0xf0, 0x01, 0xf9, 0x5e, 0xc8, 0x8e, 0x13, 0x52, 0x40, 0x54, 0x20, 0xb1, 0xf9,
	0xbd, 0xf3, 0xbb, 0xfb, 0xe9, 0x2c, 0x03, 0x64, 0x52, 0x53, 0x94, 0x17, 0x52, 0x4b, 0xf4, 0xcd,
	0x59, 0xf1, 0x47, 0xe8, 0x5c, 0x4a, 0x4d, 0xd8, 0x07, 0x4f, 0x24, 0xac, 0x35, 0x6a, 0x1d, 0x76,
	0x67, 0x9e, 0x48, 0x70, 0x00, 0xbe, 0x16, 0x3a, 0x25, 0xe6, 0x59, 0xab, 0x14, 0xc8, 0x20, 0x58,
	0x14, 0x14, 0x6b, 0x59, 0xb0, 0xb6, 0xf5, 0x2b, 0x89, 0x23, 0x08, 0x13, 0x52, 0x8b, 0x42, 0xe4,
	0x5a, 0xc8, 0x8c, 0x75, 0x6c, 0xb5, 0x69, 0xf1, 0x6b, 0xd8, 0x9e, 0x9a, 0xcb, 0x64, 0xe6, 0xcd,
	0xe8, 0xf9, 0x85, 0x94, 0xb6, 0x63, 0xe4, 0x13, 0x65, 0x6e, 0x72, 0x29, 0x30, 0x82, 0x9e, 0xa1,
	0xbb, 0x4f, 0x48, 0xc7, 0x22, 0x55, 0x96, 0x21, 0x1c, 0x87, 0x91, 0x45, 0x8e, 0x6c, 0x3e, 0x34,
	0xe7, 0xb3, 0xb2, 0xce, 0xef, 0x00, 0x9b, 0xad, 0x55, 0x2e, 0x33, 0x65, 0x61, 0x97, 0xa4, 0x54,
	0xfc, 0x40, 0xae, 0x7b, 0x25, 0x7f, 0xdd, 0xff, 0x04, 0xfa, 0x17, 0xa4, 0xd7, 0x73, 0x0f, 0xc0,
	0xa7, 0x65, 0x2c, 0xd2, 0x6a, 0x69, 0x56, 0xf0, 0x5b, 0xd8, 0xaa, 0xd3, 0x7f, 0x40, 0x6b, 0xff,
	0x88, 0x76, 0x00, 0xe1, 0x5a, 0x2e, 0x7e, 0x05, 0xbd, 0xff, 0x19, 0x3f, 0x7e, 0x6b, 0x81, 0x6f,
	0x5c, 0x85, 0x53, 0x80, 0x8f, 0x37, 0x40, 0xe6, 0x12, 0x5f, 0x5e, 0x7c, 0xb8, 0xff, 0x4d, 0xa5,
	0xc4, 0xe2, 0x1b, 0x78, 0x5a, 0x2f, 0x7a, 0xf2, 0x7a, 0x6e, 0x96, 0x87, 0xbb, 0xee, 0xfa, 0xea,
	0xfe, 0x87, 0x7b, 0x9f, 0xed, 0xba, 0xc5, 0x31, 0x04, 0xce, 0x44, 0x6c, 0x62, 0xbb, 0xe0, 0xce,
	0x8a, 0x57, 0xa5, 0x26, 0xdd, 0x9b, 0xc0, 0xfa, 0xf9, 0x7c, 0xbe, 0x69, 0xff, 0xc7, 0xd1, 0x7b,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x2e, 0xc8, 0x77, 0xaf, 0x2d, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NotesClient is the client API for Notes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NotesClient interface {
	CreateNote(ctx context.Context, in *CreateNoteRequest, opts ...grpc.CallOption) (*CreateNoteResponse, error)
	GetNoteByEmail(ctx context.Context, in *GetNoteRequest, opts ...grpc.CallOption) (*GetNoteResponse, error)
	GetNote(ctx context.Context, in *NoteRequest, opts ...grpc.CallOption) (*NoteResponse, error)
}

type notesClient struct {
	cc *grpc.ClientConn
}

func NewNotesClient(cc *grpc.ClientConn) NotesClient {
	return &notesClient{cc}
}

func (c *notesClient) CreateNote(ctx context.Context, in *CreateNoteRequest, opts ...grpc.CallOption) (*CreateNoteResponse, error) {
	out := new(CreateNoteResponse)
	err := c.cc.Invoke(ctx, "/notes.Notes/CreateNote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notesClient) GetNoteByEmail(ctx context.Context, in *GetNoteRequest, opts ...grpc.CallOption) (*GetNoteResponse, error) {
	out := new(GetNoteResponse)
	err := c.cc.Invoke(ctx, "/notes.Notes/GetNoteByEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notesClient) GetNote(ctx context.Context, in *NoteRequest, opts ...grpc.CallOption) (*NoteResponse, error) {
	out := new(NoteResponse)
	err := c.cc.Invoke(ctx, "/notes.Notes/GetNote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotesServer is the server API for Notes service.
type NotesServer interface {
	CreateNote(context.Context, *CreateNoteRequest) (*CreateNoteResponse, error)
	GetNoteByEmail(context.Context, *GetNoteRequest) (*GetNoteResponse, error)
	GetNote(context.Context, *NoteRequest) (*NoteResponse, error)
}

// UnimplementedNotesServer can be embedded to have forward compatible implementations.
type UnimplementedNotesServer struct {
}

func (*UnimplementedNotesServer) CreateNote(ctx context.Context, req *CreateNoteRequest) (*CreateNoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNote not implemented")
}
func (*UnimplementedNotesServer) GetNoteByEmail(ctx context.Context, req *GetNoteRequest) (*GetNoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNoteByEmail not implemented")
}
func (*UnimplementedNotesServer) GetNote(ctx context.Context, req *NoteRequest) (*NoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNote not implemented")
}

func RegisterNotesServer(s *grpc.Server, srv NotesServer) {
	s.RegisterService(&_Notes_serviceDesc, srv)
}

func _Notes_CreateNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotesServer).CreateNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notes.Notes/CreateNote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotesServer).CreateNote(ctx, req.(*CreateNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notes_GetNoteByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotesServer).GetNoteByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notes.Notes/GetNoteByEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotesServer).GetNoteByEmail(ctx, req.(*GetNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notes_GetNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotesServer).GetNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notes.Notes/GetNote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotesServer).GetNote(ctx, req.(*NoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Notes_serviceDesc = grpc.ServiceDesc{
	ServiceName: "notes.Notes",
	HandlerType: (*NotesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNote",
			Handler:    _Notes_CreateNote_Handler,
		},
		{
			MethodName: "GetNoteByEmail",
			Handler:    _Notes_GetNoteByEmail_Handler,
		},
		{
			MethodName: "GetNote",
			Handler:    _Notes_GetNote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "note.proto",
}
